"""artifacts_library

Revision ID: 3d85f28e55a2
Revises: 0003
Create Date: 2026-06-27 20:00:44.820526

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene_artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("artifact_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("position", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("artifacts", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("artifacts_game_id_fkey"), "artifacts", type_="foreignkey")
    op.drop_constraint(op.f("artifacts_scene_id_fkey"), "artifacts", type_="foreignkey")
    op.create_foreign_key(None, "artifacts", "users", ["owner_id"], ["id"])
    op.drop_column("artifacts", "is_active")
    op.drop_column("artifacts", "position")
    op.drop_column("artifacts", "scene_id")
    op.drop_column("artifacts", "game_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artifacts", sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "artifacts", sa.Column("scene_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "artifacts",
        sa.Column("position", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    )
    op.add_column(
        "artifacts",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "artifacts", type_="foreignkey")
    op.create_foreign_key(
        op.f("artifacts_scene_id_fkey"),
        "artifacts",
        "scenes",
        ["scene_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("artifacts_game_id_fkey"),
        "artifacts",
        "games",
        ["game_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("artifacts", "owner_id")
    op.drop_table("scene_artifacts")
    # ### end Alembic commands ###
